### ISSUE TITLE
Update requirements.txt

### ISSUE THREAD

**Issue by Danc2050** [eveem-org/panoramix#5]
Please update requirements.txt to make it easier for users to start.
**Missing**
- secret
- typing_extensions
- Others, but I installed them a while ago and forgot.

**Comment by kolinko** [comment]
"secret" is a file with private keys etc, it should be created with the first installation
"typing_extensions" is a part of the standard library since python3.6 ( https://pypi.org/project/typing-extensions/ ). Panoramix requires python3.8, so it shouldn't be in requirements

I tested requirements on a completely fresh system install, and requirements.txt seem complete (aside from the fact that web3 keeps breaking and requiring some weird hacks). If you notice anything else missing please let me know.
